#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 17 16:04:22 2020

@author: huc
"""

import cv2
img = cv2.imread('iphone.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imwrite('test1.jpg',gray)